/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package cafe.management.system;

import java.awt.Frame;
import java.util.Date;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Huawei
 */
public class DeleteDialogBill extends java.awt.Dialog {

    private EntityManagerFactory emf;
    private EntityManager em;

    String idBillLama, namaKasirLama, namaWaitersLama, namaCustomersLama, produkLama, jenisLama, statusLama;
    int poinMembershipLama, totalLama;
    Date tanggalLama;

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public DeleteDialogBill(Frame parent, boolean modal, String idBill, String namaKasir,
            String namaWaiters, String namaCustomers, int poinMembership, String produk,
            Date tanggal, int total, String jenis, String status) {
        super(parent, modal);
        initComponents();
        connect();

        this.idBillLama = idBill;
        this.namaKasirLama = namaKasir;
        this.namaWaitersLama = namaWaiters;
        this.namaCustomersLama = namaCustomers;
        this.poinMembershipLama = poinMembership;
        this.tanggalLama = tanggal;
        this.produkLama = produk;
        this.totalLama = total;
        this.jenisLama = jenis;
        this.statusLama = status;

        TxtIDBill.setText(idBill);
        TxtNamaKasir.setText(namaKasir);
        TxtNamaWaiters.setText(namaWaiters);
        TxtNamaCustomers.setText(namaCustomers);
        TxtPoin.setText(String.valueOf(poinMembership));
        DtcTanggalTransaksi.setDate(tanggal);
        TxtNamaProduk.setText(produk);
        TxtTotalHarga.setText(String.valueOf(total));
        CbJenisPembayaran.setSelectedItem(jenis);
        CbStatusPembayaran.setSelectedItem(status);

        TxtIDBill.setEditable(false);
        TxtNamaKasir.setEditable(false);
        TxtNamaWaiters.setEditable(false);
        TxtNamaCustomers.setEditable(false);
        TxtPoin.setEditable(false);
        DtcTanggalTransaksi.setEnabled(false);
        TxtNamaProduk.setEditable(false);
        TxtTotalHarga.setEditable(false);
        CbJenisPembayaran.setEnabled(false);
        CbStatusPembayaran.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtIDBill = new javax.swing.JTextField();
        TxtNamaKasir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNamaWaiters = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtNamaCustomers = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtPoin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DtcTanggalTransaksi = new com.toedter.calendar.JDateChooser();
        TxtNamaProduk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtTotalHarga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CbJenisPembayaran = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        CbStatusPembayaran = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("View Bill Order");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bill ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 62, -1));
        add(TxtIDBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 260, -1));

        TxtNamaKasir.setToolTipText("");
        add(TxtNamaKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 260, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Kasir");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Waiters");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));
        add(TxtNamaWaiters, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 260, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Customers");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 134, -1));
        add(TxtNamaCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 260, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Poin Membership");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        TxtPoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPoinActionPerformed(evt);
            }
        });
        add(TxtPoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 260, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Transaksi");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 134, -1));
        add(DtcTanggalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 260, -1));
        add(TxtNamaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 260, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Produk");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 113, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Harga");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 113, -1));
        add(TxtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 260, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jenis Pembayaran");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        CbJenisPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CbJenisPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Pembayaran", "Tunai", "Qris", "Debit", " " }));
        add(CbJenisPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 260, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status Pembayaran");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 134, -1));

        CbStatusPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CbStatusPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Status Pembayaran", "Belum Lunas", "Lunas" }));
        add(CbStatusPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 260, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ya");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 255, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Tidak");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void TxtPoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPoinActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (TxtIDBill.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "ID Bill tidak boleh kosong!");
            return;
        } else {
            EntityManagerFactory emf = null;
            EntityManager em = null;

            try {
                emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
                em = emf.createEntityManager();

                String idBill = TxtIDBill.getText();

                em.getTransaction().begin();
                Penjualan p = em.find(Penjualan.class, idBillLama);

                if (p == null) {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                } else {
                    em.remove(p);
                    em.getTransaction().commit();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    dispose();
                }
            } catch (Exception e) {
                if (em != null && em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
            } finally {
                if (em != null) {
                    em.close();
                }
                if (emf != null) {
                    emf.close();
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DeleteDialogBill dialog = new DeleteDialogBill(new java.awt.Frame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbJenisPembayaran;
    private javax.swing.JComboBox<String> CbStatusPembayaran;
    private com.toedter.calendar.JDateChooser DtcTanggalTransaksi;
    private javax.swing.JTextField TxtIDBill;
    private javax.swing.JTextField TxtNamaCustomers;
    private javax.swing.JTextField TxtNamaKasir;
    private javax.swing.JTextField TxtNamaProduk;
    private javax.swing.JTextField TxtNamaWaiters;
    private javax.swing.JTextField TxtPoin;
    private javax.swing.JTextField TxtTotalHarga;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
