/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafeManagementSystem;

import cafe.management.system.Customers;
import cafe.management.system.JenisPembayaran;
import cafe.management.system.Kasir;
import cafe.management.system.Membership;
import cafe.management.system.Pembayaran;
import cafe.management.system.Penjualan;
import cafe.management.system.Produk;
import cafe.management.system.Waiters;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huawei
 */
public class PlaceOrder extends javax.swing.JFrame {

    /**
     * Creates new form PlaceOrder
     */
    static int counter = 1;

    public PlaceOrder() {
        initComponents();
        SpJumlah.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hitungTotalHargaItem();
            }
        });
        LblPoinMember.setVisible(false);
        TxtPoin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtIDPembayaran = new javax.swing.JTextField();
        BtnSearchKasir = new javax.swing.JButton();
        BtnSearchWaiters = new javax.swing.JButton();
        TxtIDWaiters = new javax.swing.JTextField();
        LblIDWaiters = new javax.swing.JLabel();
        TxtIDKasir = new javax.swing.JTextField();
        LblIDKasir = new javax.swing.JLabel();
        TxtNamaKasir = new javax.swing.JTextField();
        LblNamaKasir = new javax.swing.JLabel();
        TxtIDMember = new javax.swing.JTextField();
        LblIDMember = new javax.swing.JLabel();
        BtnCari = new javax.swing.JButton();
        TxtIDBill = new javax.swing.JTextField();
        BtnSearchProduk = new javax.swing.JButton();
        DtcTransaksi = new com.toedter.calendar.JDateChooser();
        TxtIDProduk = new javax.swing.JTextField();
        LblIDProduk = new javax.swing.JLabel();
        TxtStatusPembayaran = new javax.swing.JTextField();
        TxtPoin = new javax.swing.JTextField();
        LblPoinMember = new javax.swing.JLabel();
        LblStatusPembayaran = new javax.swing.JLabel();
        BtnCariPembayaran = new javax.swing.JButton();
        LblJenisPembayaran = new javax.swing.JLabel();
        LblTglTransaksi = new javax.swing.JLabel();
        TxtNamaWaiters = new javax.swing.JTextField();
        LblNamaWaiters = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LblIDCustomer = new javax.swing.JLabel();
        TxtJnsPembayaran = new javax.swing.JTextField();
        TxtIDCustomer = new javax.swing.JTextField();
        TxtNamaCustomer = new javax.swing.JTextField();
        LblNamaCustomer = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LblNamaProduk = new javax.swing.JLabel();
        TxtNamaProduk = new javax.swing.JTextField();
        LblSubTotal = new javax.swing.JLabel();
        TxtHarga = new javax.swing.JTextField();
        LblJumlah = new javax.swing.JLabel();
        LblTotalHarga = new javax.swing.JLabel();
        SpJumlah = new javax.swing.JSpinner();
        TxtTotalHarga = new javax.swing.JTextField();
        BtnClear = new javax.swing.JButton();
        BtnKeranjang = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablePesanan = new javax.swing.JTable();
        LblGrandTotal = new javax.swing.JLabel();
        BtnPrintBill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        LblTotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(TxtIDPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 60, 30));

        BtnSearchKasir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSearchKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        BtnSearchKasir.setText("Search");
        BtnSearchKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchKasirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSearchKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, 30));

        BtnSearchWaiters.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSearchWaiters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        BtnSearchWaiters.setText("Search");
        BtnSearchWaiters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchWaitersActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSearchWaiters, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, 30));
        getContentPane().add(TxtIDWaiters, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, 30));

        LblIDWaiters.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblIDWaiters.setForeground(new java.awt.Color(255, 255, 255));
        LblIDWaiters.setText("ID Waiters");
        getContentPane().add(LblIDWaiters, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        getContentPane().add(TxtIDKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 30));

        LblIDKasir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblIDKasir.setForeground(new java.awt.Color(255, 255, 255));
        LblIDKasir.setText("ID Kasir");
        getContentPane().add(LblIDKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));
        getContentPane().add(TxtNamaKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 250, 30));

        LblNamaKasir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNamaKasir.setForeground(new java.awt.Color(255, 255, 255));
        LblNamaKasir.setText("Nama Kasir");
        getContentPane().add(LblNamaKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));
        getContentPane().add(TxtIDMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 120, 30));

        LblIDMember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblIDMember.setForeground(new java.awt.Color(255, 255, 255));
        LblIDMember.setText("ID Membership");
        getContentPane().add(LblIDMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        BtnCari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        BtnCari.setText("Search");
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, -1, 30));
        getContentPane().add(TxtIDBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 90, -1));

        BtnSearchProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSearchProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        BtnSearchProduk.setText("Search");
        BtnSearchProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchProdukActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSearchProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 70, -1, -1));
        getContentPane().add(DtcTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 250, 30));

        TxtIDProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDProdukActionPerformed(evt);
            }
        });
        getContentPane().add(TxtIDProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 160, 30));

        LblIDProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblIDProduk.setForeground(new java.awt.Color(255, 255, 255));
        LblIDProduk.setText("ID Produk");
        getContentPane().add(LblIDProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, -1, -1));

        TxtStatusPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStatusPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(TxtStatusPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 100, 30));
        getContentPane().add(TxtPoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 250, 30));

        LblPoinMember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblPoinMember.setForeground(new java.awt.Color(255, 255, 255));
        LblPoinMember.setText("Poin Membership");
        getContentPane().add(LblPoinMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

        LblStatusPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblStatusPembayaran.setForeground(new java.awt.Color(255, 255, 255));
        LblStatusPembayaran.setText("Status Pembayaran");
        getContentPane().add(LblStatusPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        BtnCariPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCariPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        BtnCariPembayaran.setText("Search");
        BtnCariPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCariPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        LblJenisPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblJenisPembayaran.setForeground(new java.awt.Color(255, 255, 255));
        LblJenisPembayaran.setText("Jenis Pembayaran");
        getContentPane().add(LblJenisPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, 30));

        LblTglTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblTglTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        LblTglTransaksi.setText("Tanggal Transaksi");
        getContentPane().add(LblTglTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 20));

        TxtNamaWaiters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaWaitersActionPerformed(evt);
            }
        });
        getContentPane().add(TxtNamaWaiters, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 250, 30));

        LblNamaWaiters.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNamaWaiters.setForeground(new java.awt.Color(255, 255, 255));
        LblNamaWaiters.setText("Nama Waiters");
        getContentPane().add(LblNamaWaiters, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 120, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        jLabel1.setText("Place Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 21, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bil ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 48, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Details:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        LblIDCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblIDCustomer.setForeground(new java.awt.Color(255, 255, 255));
        LblIDCustomer.setText("ID Customers");
        getContentPane().add(LblIDCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 100, -1));
        getContentPane().add(TxtJnsPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 100, 30));

        TxtIDCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TxtIDCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(TxtIDCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 251, -1));

        TxtNamaCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(TxtNamaCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 251, -1));

        LblNamaCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNamaCustomer.setForeground(new java.awt.Color(255, 255, 255));
        LblNamaCustomer.setText("Nama Customers");
        getContentPane().add(LblNamaCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 133, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1322, 21, -1, -1));

        LblNamaProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNamaProduk.setForeground(new java.awt.Color(255, 255, 255));
        LblNamaProduk.setText("Nama Produk");
        getContentPane().add(LblNamaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 110, -1));

        TxtNamaProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TxtNamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaProdukActionPerformed(evt);
            }
        });
        getContentPane().add(TxtNamaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 251, -1));

        LblSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        LblSubTotal.setText("SubTotal");
        getContentPane().add(LblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 90, -1));

        TxtHarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(TxtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, 251, -1));

        LblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblJumlah.setForeground(new java.awt.Color(255, 255, 255));
        LblJumlah.setText("Jumlah");
        getContentPane().add(LblJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 94, -1));

        LblTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblTotalHarga.setForeground(new java.awt.Color(255, 255, 255));
        LblTotalHarga.setText("Total Harga");
        getContentPane().add(LblTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 170, 100, -1));
        getContentPane().add(SpJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 251, -1));

        TxtTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TxtTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalHargaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 200, 251, -1));

        BtnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(BtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, -1, -1));

        BtnKeranjang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnKeranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        BtnKeranjang.setText("Add to Cart");
        BtnKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeranjangActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKeranjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 250, -1, -1));

        TablePesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Produk", "Nama Produk", "SubTotal", "Jumlah Produk", "Total Harga"
            }
        ));
        jScrollPane2.setViewportView(TablePesanan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 572, 320));

        LblGrandTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblGrandTotal.setForeground(new java.awt.Color(255, 255, 255));
        LblGrandTotal.setText("Grand Total: Rp.");
        getContentPane().add(LblGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 650, 120, 20));

        BtnPrintBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPrintBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        BtnPrintBill.setText("Generate Bill & Print");
        BtnPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintBillActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPrintBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 650, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 250, 260));

        LblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblTotal.setForeground(new java.awt.Color(255, 255, 255));
        LblTotal.setText("000");
        LblTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblTotalMouseClicked(evt);
            }
        });
        getContentPane().add(LblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, 70, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIDCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDCustomerActionPerformed

    public void hitungTotalHargaItem() {
        try {
            int harga = Integer.parseInt(TxtHarga.getText());
            int jumlah = (int) SpJumlah.getValue();

            if (jumlah < 0) {
                jumlah = 0;
                SpJumlah.setValue(0);
            }

            int total = harga * jumlah;
            TxtTotalHarga.setText(String.valueOf(total));

        } catch (NumberFormatException ex) {
            TxtTotalHarga.setText("0");
        }
    }

    private void TxtTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalHargaActionPerformed
        try {
            int harga = Integer.parseInt(TxtHarga.getText());
            int jumlah = (int) SpJumlah.getValue();
            int total = harga * jumlah;

            TxtTotalHarga.setText(String.valueOf(total));
        } catch (Exception ex) {
            // ignore
        }
    }//GEN-LAST:event_TxtTotalHargaActionPerformed

    private void cetakBill() {

        String idBill = TxtIDBill.getText();
        String idCustomer = TxtIDCustomer.getText();
        String namaCustomer = TxtNamaCustomer.getText();
        String membership = TxtPoin.getText();
        String total = TxtTotalHarga.getText();
        String bayar = LblTotal.getText();

        jTextArea1.setText(""); // Kosongkan dulu

        StringBuilder bill = new StringBuilder();

        bill.append("=====================================\n");
        bill.append("                CAFE XYZ\n");
        bill.append("=====================================\n");
        bill.append("ID BILL       : ").append(idBill).append("\n");
        bill.append("ID CUSTOMER   : ").append(idCustomer).append("\n");
        bill.append("Nama Customer : ").append(namaCustomer).append("\n");
        bill.append("Membership    : ").append(membership).append("\n");
        bill.append("-------------------------------------\n");
        bill.append("Items:\n");

        // ----- Ambil daftar item dari JTable ----
        for (int i = 0; i < TablePesanan.getRowCount(); i++) {
            String id = TablePesanan.getValueAt(i, 1).toString();
            String namaItem = TablePesanan.getValueAt(i, 2).toString();
            String subtotal = TablePesanan.getValueAt(i, 3).toString();
            String qty = TablePesanan.getValueAt(i, 4).toString();
            String harga = TablePesanan.getValueAt(i, 5).toString();

            bill.append(namaItem)
                    .append("   x").append(qty)
                    .append("   @").append(harga)
                    .append("   = ").append(subtotal)
                    .append("\n");
        }

        bill.append("-------------------------------------\n");
        bill.append("Total Harga  : ").append(total).append("\n");
        bill.append("Bayar        : ").append(bayar).append("\n");
        bill.append("=====================================\n");
        bill.append("       TERIMA KASIH SUDAH BELANJA\n");
        bill.append("=====================================\n");

        jTextArea1.setText(bill.toString());
    }


    private void BtnPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintBillActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
        EntityManager em = emf.createEntityManager();

        try {
            em.getTransaction().begin();

            //id Kasir
            String idKasir = TxtIDKasir.getText();
            if (idKasir == null || idKasir.equals("--")) {
                String LastId = "";
                try {
                    LastId = em.createQuery("SELECT k FROM Kasir k WHERE k.idKasir = :idKasir", String.class)
                            .setMaxResults(1)
                            .getSingleResult();
                } catch (Exception e) {
                    LastId = null;
                }
            }

            //id Jenis pembayaran
            String idJenis = TxtIDPembayaran.getText();
            if (idJenis == null || idJenis.equals("--")) {
                String LastId = "";
                try {
                    LastId = em.createQuery("SELECT j FROM JenisPembayaran j WHERE j.idJenis = :idJenis", String.class)
                            .setMaxResults(1)
                            .getSingleResult();
                } catch (Exception e) {
                    LastId = null;
                }
            }

            //id penjualan
            String idBill = TxtIDBill.getText();
            if (idBill == null || idBill.equals("--")) {
                String lastId = "";
                try {
                    lastId = em.createQuery(
                            "SELECT p.idPenjualan FROM Penjualan p ORDER BY p.idPenjualan DESC", String.class)
                            .setMaxResults(1)
                            .getSingleResult();
                } catch (Exception e) {
                    lastId = null;
                }
                int nextNumber = 1;

                if (lastId != null && lastId.startsWith("S")) {
                    nextNumber = Integer.parseInt(lastId.substring(1)) + 1;
                }
                idBill = String.format("S%03d", nextNumber);
                TxtIDBill.setText(idBill);
            }

            int grandTotal = 0;
            try {
                String totalText = LblTotal.getText();
                if (totalText != null && !totalText.trim().isEmpty()) {
                    grandTotal = Integer.parseInt(totalText.trim());
                }
            } catch (NumberFormatException nfe) {
                grandTotal = 0;
            }

            Penjualan p = new Penjualan();
            p.setIdPenjualan(idBill);
            p.setTanggalPenjualan(DtcTransaksi.getDate());
            p.setTotalHarga(grandTotal);
            p.setProdukCollection(cart);

            String inputCustomerId = TxtIDCustomer.getText();
            Customers c = null;
            if (inputCustomerId != null && !inputCustomerId.trim().isEmpty()) {
                c = em.find(Customers.class, inputCustomerId.trim());
            }
            if (c == null) {

                String newCustId = (inputCustomerId != null && !inputCustomerId.trim().isEmpty())
                        ? inputCustomerId.trim()
                        : "C" + System.currentTimeMillis();

                c = new Customers();
                c.setIdCustomers(newCustId);

                String namaCust = TxtNamaCustomer.getText();
                if (namaCust == null) {
                    namaCust = "";
                }
                c.setNamaCustomers(namaCust);

                em.persist(c);
            }
            p.setIdCustomers(c);

            String idWaitersInput = TxtIDWaiters.getText();
            if (idWaitersInput != null && !idWaitersInput.trim().isEmpty()) {
                Waiters w = em.find(Waiters.class, idWaitersInput.trim());

                if (w != null) {
                    p.setIdWaiters(w);
                } else {
                    System.out.println("Waiter tidak ditemukan untuk input ID: " + idWaitersInput + "/" + TxtNamaWaiters.getText());
                }
            }

            String idKasirInput = TxtIDKasir.getText();
            if (idKasirInput != null && !idKasirInput.trim().isEmpty()) {
                Kasir k = em.find(Kasir.class, idKasirInput.trim());

                if (k != null) {
                    p.setIdKasir(k);
                } else {
                    System.out.println("Kasir tidak ditemukan untuk input ID: " + idWaitersInput + "/" + TxtNamaKasir.getText());
                }
            }

            em.persist(p);

            Pembayaran pay = new Pembayaran();
            pay.setIdPembayaran("PB" + idBill);
            pay.setIdPenjualan(p);
            pay.setIdJenis(em.find(JenisPembayaran.class, TxtIDPembayaran.getText()));
            pay.setIdKasir(em.find(Kasir.class, TxtIDKasir.getText()));
            pay.setTanggalBayar(new Date());
            String totalText = LblTotal.getText();
            if (totalText == null || totalText.trim().isEmpty()) {
                totalText = "0";
            }
            BigInteger totalBayar = new BigInteger(totalText.trim());
            pay.setTotalBayar(totalBayar);
            pay.setStatusBayar(TxtStatusPembayaran.getText() == null ? "" : TxtStatusPembayaran.getText().trim());

            em.persist(pay);

            em.getTransaction().commit();
            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");
            cart.clear(); // kosongkan keranjang
            ((DefaultTableModel) TablePesanan.getModel()).setRowCount(0);
            cetakBill();
        } catch (Exception ex) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            } else {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error saat menyimpan transaksi: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

            if (em.isOpen()) {
                em.close();
            }
            if (emf.isOpen()) {
                emf.close();
            }
        }
        bersih1();
    }//GEN-LAST:event_BtnPrintBillActionPerformed

    private List<Produk> cart = new ArrayList<>();

    private void bersih1() {
        TxtIDBill.setText("");
        TxtIDCustomer.setText("");
        TxtIDKasir.setText("");
        TxtIDWaiters.setText("");
        TxtIDMember.setText("");
        TxtNamaKasir.setText("");
        TxtPoin.setText("");
        TxtNamaCustomer.setText("");
        TxtNamaWaiters.setText("");
        TxtStatusPembayaran.setText("");
        TxtIDPembayaran.setText("");
        TxtJnsPembayaran.setText("");
        LblTotal.setText("0");

        DefaultTableModel model = (DefaultTableModel) TablePesanan.getModel();
        model.setRowCount(0);

        DtcTransaksi.setDate(null);

        TxtIDBill.requestFocus();
    }

    private void bersih() {
        TxtIDProduk.setText("");
        TxtNamaProduk.setText("");
        TxtHarga.setText("");
        TxtTotalHarga.setText("");
        SpJumlah.setValue(1);
    }

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        bersih();
    }//GEN-LAST:event_BtnClearActionPerformed

    private void TxtNamaWaitersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaWaitersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaWaitersActionPerformed

    private void TxtIDProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDProdukActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
        EntityManager em = emf.createEntityManager();

        try {
            String id = TxtIDProduk.getText();

            Produk p = em.find(Produk.class, id);

            if (p != null) {
                TxtNamaProduk.setText(p.getNamaProduk());
                TxtHarga.setText(String.valueOf(p.getHargaProduk()));
            } else {
                JOptionPane.showMessageDialog(this, "Produk tidak ditemukan");
            }
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_TxtIDProdukActionPerformed

    private void hitungGrandTotal() {
        int grandTotal = 0;

        DefaultTableModel model = (DefaultTableModel) TablePesanan.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            int totalItem = Integer.parseInt(model.getValueAt(i, 4).toString());
            grandTotal += totalItem;
        }
        LblTotal.setText(String.valueOf(grandTotal));
    }

    private void BtnKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeranjangActionPerformed
        String id = TxtIDProduk.getText();
        String namaProduk = TxtNamaProduk.getText();
        String harga = TxtHarga.getText();
        String jumlah = SpJumlah.getValue().toString();
        String total = TxtTotalHarga.getText();

        if (namaProduk.equals("") || jumlah.equals("0")) {
            JOptionPane.showMessageDialog(this, "Data produk belum lengkap!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) TablePesanan.getModel();
        model.addRow(new Object[]{
            id,
            namaProduk,
            harga,
            jumlah,
            total
        });

        hitungGrandTotal();

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
        EntityManager em = emf.createEntityManager();
        Produk p = em.find(Produk.class, id); // cari produk dari database
        cart.add(p);

        TxtIDProduk.setText("");
        TxtNamaProduk.setText("");
        TxtHarga.setText("");
        TxtTotalHarga.setText("");
        SpJumlah.setValue(1);
    }//GEN-LAST:event_BtnKeranjangActionPerformed

    private void LblTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LblTotalMouseClicked

    private void TxtNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaProdukActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnSearchProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchProdukActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
        EntityManager em = emf.createEntityManager();

        try {
            String id = TxtIDProduk.getText();
            Produk p = em.find(Produk.class, id);

            if (p != null) {
                TxtNamaProduk.setText(p.getNamaProduk());
                TxtHarga.setText(String.valueOf(p.getHargaProduk()));
                SpJumlah.setValue(1);

                int harga = p.getHargaProduk();
                TxtTotalHarga.setText(String.valueOf(harga));

            } else {
                JOptionPane.showMessageDialog(this, "Produk dengan ID: " + id + " tidak ditemukan", "Pencarian Produk", JOptionPane.ERROR_MESSAGE);
                bersih();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error saat mencari produk: " + ex.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_BtnSearchProdukActionPerformed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        if (TxtIDMember.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Terlebih Dahulu");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            String user = TxtIDMember.getText();
            Membership y = em.find(Membership.class, user);

            if (y == null) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                TxtIDMember.requestFocus();
            } else {
                int poin = y.getPoinMember();
                TxtPoin.setText(String.valueOf(poin));

                LblPoinMember.setVisible(true);
                TxtPoin.setVisible(true);
                TxtIDMember.setEditable(false);
                TxtPoin.requestFocus();
            }
            em.getTransaction().commit();
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnSearchKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchKasirActionPerformed
        if (TxtIDKasir.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Terlebih Dahulu");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            String user = TxtIDKasir.getText();
            Kasir y = em.find(Kasir.class, user);

            if (y == null) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                TxtIDKasir.requestFocus();
            } else {
                TxtNamaKasir.setText(y.getNamaKasir());

                TxtIDKasir.setEditable(false);
                TxtNamaKasir.requestFocus();
            }
            em.getTransaction().commit();
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_BtnSearchKasirActionPerformed

    private void BtnSearchWaitersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchWaitersActionPerformed
        if (TxtIDWaiters.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Terlebih Dahulu");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            String user = TxtIDWaiters.getText();
            Waiters y = em.find(Waiters.class, user);

            if (y == null) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                TxtIDWaiters.requestFocus();
            } else {
                TxtNamaWaiters.setText(y.getNamaWaiters());

                TxtIDWaiters.setEditable(false);
                TxtNamaWaiters.requestFocus();
            }
            em.getTransaction().commit();
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_BtnSearchWaitersActionPerformed

    private void BtnCariPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariPembayaranActionPerformed
        if (TxtIDPembayaran.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Terlebih Dahulu");
            return;
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            String user = TxtIDPembayaran.getText().trim();
            JenisPembayaran y = em.find(JenisPembayaran.class, user);

            if (y == null) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                TxtIDPembayaran.requestFocus();
                TxtJnsPembayaran.setText("");
                TxtStatusPembayaran.setText("Belum Lunas");
            } else {
                TxtJnsPembayaran.setText(y.getNamaJenis());
                TxtStatusPembayaran.setText("Lunas");
                Pembayaran pembayaran = new Pembayaran();
                pembayaran.setIdJenis(y); 
                pembayaran.setTanggalBayar(new Date());

//                pembayaran.setTotalBayar(BigInteger.valueOf(NORMAL));
//                pembayaran.setIdKasir(idKasir);
//                pembayaran.setIdPenjualan(penjualan);
                TxtIDPembayaran.setEditable(false);
                TxtJnsPembayaran.requestFocus();
            }
            em.getTransaction().commit();
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_BtnCariPembayaranActionPerformed

    private void TxtStatusPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStatusPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStatusPembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCari;
    private javax.swing.JButton BtnCariPembayaran;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnKeranjang;
    private javax.swing.JButton BtnPrintBill;
    private javax.swing.JButton BtnSearchKasir;
    private javax.swing.JButton BtnSearchProduk;
    private javax.swing.JButton BtnSearchWaiters;
    private com.toedter.calendar.JDateChooser DtcTransaksi;
    private javax.swing.JLabel LblGrandTotal;
    private javax.swing.JLabel LblIDCustomer;
    private javax.swing.JLabel LblIDKasir;
    private javax.swing.JLabel LblIDMember;
    private javax.swing.JLabel LblIDProduk;
    private javax.swing.JLabel LblIDWaiters;
    private javax.swing.JLabel LblJenisPembayaran;
    private javax.swing.JLabel LblJumlah;
    private javax.swing.JLabel LblNamaCustomer;
    private javax.swing.JLabel LblNamaKasir;
    private javax.swing.JLabel LblNamaProduk;
    private javax.swing.JLabel LblNamaWaiters;
    private javax.swing.JLabel LblPoinMember;
    private javax.swing.JLabel LblStatusPembayaran;
    private javax.swing.JLabel LblSubTotal;
    private javax.swing.JLabel LblTglTransaksi;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JLabel LblTotalHarga;
    private javax.swing.JSpinner SpJumlah;
    private javax.swing.JTable TablePesanan;
    private javax.swing.JTextField TxtHarga;
    private javax.swing.JTextField TxtIDBill;
    private javax.swing.JTextField TxtIDCustomer;
    private javax.swing.JTextField TxtIDKasir;
    private javax.swing.JTextField TxtIDMember;
    private javax.swing.JTextField TxtIDPembayaran;
    private javax.swing.JTextField TxtIDProduk;
    private javax.swing.JTextField TxtIDWaiters;
    private javax.swing.JTextField TxtJnsPembayaran;
    private javax.swing.JTextField TxtNamaCustomer;
    private javax.swing.JTextField TxtNamaKasir;
    private javax.swing.JTextField TxtNamaProduk;
    private javax.swing.JTextField TxtNamaWaiters;
    private javax.swing.JTextField TxtPoin;
    private javax.swing.JTextField TxtStatusPembayaran;
    private javax.swing.JTextField TxtTotalHarga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
