/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package cafe.management.system;

import java.awt.Frame;
import java.util.*;
import javax.swing.table.*;
import javax.swing.*;
import javax.persistence.*;
import java.text.*;

/**
 *
 * @author Huawei
 */
public class UpdateDialogBill extends java.awt.Dialog {

    private EntityManagerFactory emf;
    private EntityManager em;

    String idBillLama, namaKasirLama, namaWaitersLama, namaCustomersLama, produkLama, jenisLama, statusLama;
    int poinMembershipLama, totalLama;
    Date tanggalLama;

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public UpdateDialogBill(Frame parent, boolean modal, String idBill, String namaKasir,
            String namaWaiters, String namaCustomers, int poinMembership, String produk, Date tanggal,
            int total, String jenis, String status) {
        super(parent, modal);
        initComponents();
        connect();
        cekCustomerMembership();

        this.idBillLama = idBill;
        this.namaKasirLama = namaKasir;
        this.namaWaitersLama = namaWaiters;
        this.namaCustomersLama = namaCustomers;
        this.poinMembershipLama = poinMembership;
        this.tanggalLama = tanggal;
        this.produkLama = produk;
        this.totalLama = total;
        this.jenisLama = jenis;
        this.statusLama = status;

        TxtIDBill.setText(idBill);
        TxtNamaKasir.setText(namaKasir);
        TxtNamaWaiters.setText(namaWaiters);
        TxtNamaCustomers.setText(namaCustomers);
        TxtPoin.setText(String.valueOf(poinMembership));
        DtcTanggalTransaksi.setDate(tanggal);
        TxtNamaProduk.setText(produk);
        TxtTotalHarga.setText(String.valueOf(total));
        CbJenisPembayaran.setSelectedItem(jenis);
        CbStatusPembayaran.setSelectedItem(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtIDBill = new javax.swing.JTextField();
        TxtNamaKasir = new javax.swing.JTextField();
        TxtNamaWaiters = new javax.swing.JTextField();
        TxtNamaCustomers = new javax.swing.JTextField();
        TxtPoin = new javax.swing.JTextField();
        DtcTanggalTransaksi = new com.toedter.calendar.JDateChooser();
        TxtNamaProduk = new javax.swing.JTextField();
        TxtTotalHarga = new javax.swing.JTextField();
        CbJenisPembayaran = new javax.swing.JComboBox<>();
        CbStatusPembayaran = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        BtnUpdateData = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bill ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 62, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Kasir");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Waiters");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Customers");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 134, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Poin Membership");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Transaksi");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 134, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Produk");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 113, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Harga");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 113, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jenis Pembayaran");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status Pembayaran");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 134, -1));
        add(TxtIDBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 260, -1));

        TxtNamaKasir.setToolTipText("");
        add(TxtNamaKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 260, -1));
        add(TxtNamaWaiters, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 260, -1));
        add(TxtNamaCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 260, -1));
        add(TxtPoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 260, -1));
        add(DtcTanggalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 260, -1));
        add(TxtNamaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 260, -1));
        add(TxtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 260, -1));

        CbJenisPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CbJenisPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Pembayaran", "Tunai", "Qris", "Debit", " " }));
        add(CbJenisPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 260, -1));

        CbStatusPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CbStatusPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Status Pembayaran", "Belum Lunas", "Lunas" }));
        add(CbStatusPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 260, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("View Bill Order");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        BtnUpdateData.setBackground(new java.awt.Color(255, 255, 0));
        BtnUpdateData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnUpdateData.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdateData.setText("Update");
        BtnUpdateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateDataActionPerformed(evt);
            }
        });
        add(BtnUpdateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void BtnUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateDataActionPerformed

        if (TxtIDBill.getText().trim().equals("")
                || TxtNamaKasir.getText().trim().equals("")
                || TxtNamaWaiters.getText().trim().equals("")
                || TxtNamaCustomers.getText().trim().equals("")
                || TxtPoin.getText().trim().equals("")
                || DtcTanggalTransaksi.getDate() == null
                || TxtNamaProduk.getText().trim().equals("")
                || TxtTotalHarga.getText().trim().equals("")
                || CbJenisPembayaran.getSelectedIndex() == 0
                || CbStatusPembayaran.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
            return;
        }

        try {

            String idBillBaru = TxtIDBill.getText().trim();
            String kasirBaru = TxtNamaKasir.getText().trim().toLowerCase();
            String waiterBaru = TxtNamaWaiters.getText().trim().toLowerCase();
            String customerBaru = TxtNamaCustomers.getText().trim().toLowerCase();
            int poinBaru = Integer.parseInt(TxtPoin.getText().trim());
            Date tanggalBaru = DtcTanggalTransaksi.getDate();
            String produkBaru = TxtNamaProduk.getText().trim();
            int totalBaru = Integer.parseInt(TxtTotalHarga.getText().trim());
            String jenisBayarBaru = CbJenisPembayaran.getSelectedItem().toString();
            String statusBayarBaru = CbStatusPembayaran.getSelectedItem().toString();

            em.getTransaction().begin();

            if (!idBillBaru.equals(idBillLama)) {
                JOptionPane.showMessageDialog(this, "ID Bill tidak boleh diubah!");
                TxtIDBill.setText(idBillLama);
                em.getTransaction().rollback();
                return;
            }

            Penjualan p = em.find(Penjualan.class, idBillLama);
            if (p == null) {
                JOptionPane.showMessageDialog(this, "Data Bill tidak ditemukan!");
                em.getTransaction().rollback();
                return;
            }

            TypedQuery<Kasir> qKasir = em.createQuery(
                    "SELECT k FROM Kasir k WHERE LOWER(k.namaKasir)=:nm", Kasir.class);
            qKasir.setParameter("nm", kasirBaru);

            List<Kasir> listKasir = qKasir.getResultList();
            if (listKasir.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama Kasir tidak ditemukan!");
                em.getTransaction().rollback();
                return;
            }
            Kasir k = listKasir.get(0);

            TypedQuery<Waiters> qWait = em.createQuery(
                    "SELECT w FROM Waiters w WHERE LOWER(w.namaWaiters)=:nm", Waiters.class);
            qWait.setParameter("nm", waiterBaru);

            List<Waiters> listWait = qWait.getResultList();
            if (listWait.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama Waiters tidak ditemukan!");
                em.getTransaction().rollback();
                return;
            }
            Waiters w = listWait.get(0);

            TypedQuery<Customers> qCust = em.createQuery(
                    "SELECT c FROM Customers c WHERE LOWER(c.namaCustomers)=:nm", Customers.class);
            qCust.setParameter("nm", customerBaru);

            List<Customers> listCust = qCust.getResultList();
            if (listCust.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama Customers tidak ditemukan!");
                em.getTransaction().rollback();
                return;
            }
            Customers c = listCust.get(0);

            Membership m = c.getIdMember();

            if (m == null) {
                if (poinBaru != poinMembershipLama) {
                    JOptionPane.showMessageDialog(this,
                            "Customer ini bukan member. Poin tidak boleh diubah!");
                    em.getTransaction().rollback();
                    return;
                }
            } else {
                m.setPoinMember(poinBaru);
                em.merge(m);
            }

            Collection<Produk> produkCollection = getlistNamaProduk(produkBaru);

            for (Produk oldP : p.getProdukCollection()) {
                oldP.getPenjualanCollection().remove(p);
                em.merge(oldP);
            }

            for (Produk np : produkCollection) {
                np.getPenjualanCollection().add(p);
                em.merge(np);
            }

            Pembayaran pay = p.getPembayaranCollection().iterator().next();

            TypedQuery<JenisPembayaran> qJenis = em.createQuery(
                    "SELECT j FROM JenisPembayaran j WHERE LOWER(j.namaJenis)=:nm",
                    JenisPembayaran.class);
            qJenis.setParameter("nm", jenisBayarBaru.toLowerCase());
            List<JenisPembayaran> jenisList = qJenis.getResultList();

            if (!jenisList.isEmpty()) {
                pay.setIdJenis(jenisList.get(0));
            }

            pay.setStatusBayar(statusBayarBaru);
            pay.setTotalBayar(java.math.BigInteger.valueOf(totalBaru));
            em.merge(pay);

            p.setIdKasir(k);
            p.setIdWaiters(w);
            p.setIdCustomers(c);
            p.setTanggalPenjualan(tanggalBaru);
            p.setProdukCollection(produkCollection);
            p.setTotalHarga(totalBaru);

            em.merge(p);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            dispose();

        } catch (Exception ex) {
            ex.printStackTrace();
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
        }
    }//GEN-LAST:event_BtnUpdateDataActionPerformed

    private Collection<Produk> getlistNamaProduk(String produkString) {
        Collection<Produk> list = new ArrayList<>();

        if (produkString == null || produkString.trim().isEmpty()) {
            return list;
        }
        String[] namaProdukArray = produkString.split(",");

        EntityManager em = emf.createEntityManager();

        for (String nama : namaProdukArray) {
            String namaTrim = nama.trim().toLowerCase();

            try {
                Query q = em.createQuery("SELECT p FROM Produk p WHERE LOWER(p.namaProduk) = :nm");
                q.setParameter("nm", namaTrim);

                List<Produk> hasil = q.getResultList();
                if (!hasil.isEmpty()) {
                    list.add(hasil.get(0));
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        em.close();
        return list;
    }

    private void cekCustomerMembership() {
        try {
            String namaCust = TxtNamaCustomers.getText().trim().toLowerCase();

            if (namaCust.isEmpty()) {
                TxtPoin.setEnabled(false);
                TxtPoin.setText("");
                return;
            }
            EntityManager em = emf.createEntityManager();

            TypedQuery<Customers> q = em.createQuery(
                    "SELECT c FROM Customers c WHERE LOWER(c.namaCustomers) = :nm",
                    Customers.class
            );
            q.setParameter("nm", namaCust);

            List<Customers> list = q.getResultList();

            if (list.isEmpty()) {
                TxtPoin.setEnabled(false);
                TxtPoin.setText("");
                return;
            }

            Customers c = list.get(0);
            if (c.getIdMember() == null) {
                TxtPoin.setEnabled(false);
                TxtPoin.setText("0");
            } else {
                TxtPoin.setEnabled(true);
                TxtPoin.setText(String.valueOf(c.getIdMember().getPoinMember()));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    //    public static void main(String args[]) {
    //        java.awt.EventQueue.invokeLater(new Runnable() {
    //            public void run() {
    //                UpdateDialogBill dialog = new UpdateDialogBill(new java.awt.Frame(), true);
    //                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    //                    public void windowClosing(java.awt.event.WindowEvent e) {
    //                        System.exit(0);
    //                    }
    //                });
    //                dialog.setVisible(true);
    //            }
    //        });
    //    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnUpdateData;
    private javax.swing.JComboBox<String> CbJenisPembayaran;
    private javax.swing.JComboBox<String> CbStatusPembayaran;
    private com.toedter.calendar.JDateChooser DtcTanggalTransaksi;
    private javax.swing.JTextField TxtIDBill;
    private javax.swing.JTextField TxtNamaCustomers;
    private javax.swing.JTextField TxtNamaKasir;
    private javax.swing.JTextField TxtNamaProduk;
    private javax.swing.JTextField TxtNamaWaiters;
    private javax.swing.JTextField TxtPoin;
    private javax.swing.JTextField TxtTotalHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
