/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huawei
 */
public class ViewEditDeleteProduct extends javax.swing.JFrame {

    private EntityManagerFactory emf;
    private EntityManager em;
    String idproduk, namaproduk;
    Date tanggalmasukproduk;
    int hargaproduk;

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public ViewEditDeleteProduct() {
        initComponents();
        connect();
        showTable();

    }

    public void showTable() {
        DefaultTableModel tbmk;

        try {
            em.clear();
            EntityManager em = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU").createEntityManager();
            Query q = em.createNamedQuery("Produk.findAll");
            List<Produk> hasil = q.getResultList();

            tbmk = new DefaultTableModel(
                    new String[]{"ID Produk", "Nama Produk", "Harga Produk", "Tanggal Masuk Produk"}, 0
            );
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
            for (Produk data : hasil) {
                String tanggalFormatted = "";
                if (data.getTanggalMasukProduk() != null) {
                    tanggalFormatted = sdf.format(data.getTanggalMasukProduk());
                }
                Object[] baris = new Object[4];
                baris[0] = data.getIdProduk();
                baris[1] = data.getNamaProduk();
                baris[2] = data.getHargaProduk();
                baris[3] = tanggalFormatted;
                tbmk.addRow(baris);
            }

            jTable1.setModel(tbmk);
            jTable1.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tampil data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtIDProduk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtNamaProduk = new javax.swing.JTextField();
        TxtHargaProduk = new javax.swing.JTextField();
        DtcTanggalMasuk = new com.toedter.calendar.JDateChooser();
        BtnUpdateProduk = new javax.swing.JButton();
        BtnDeleteProduk = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        jLabel1.setText("View, Edit & Delete Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 16, 233, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1329, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Produk");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 254, 68, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Produk");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 295, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Produk");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 339, 110, -1));

        TxtIDProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDProdukActionPerformed(evt);
            }
        });
        getContentPane().add(TxtIDProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 310, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Masuk Produk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 383, 170, -1));

        TxtNamaProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(TxtNamaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 292, 310, -1));
        getContentPane().add(TxtHargaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 310, -1));
        getContentPane().add(DtcTanggalMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 310, -1));

        BtnUpdateProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnUpdateProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        BtnUpdateProduk.setText("Update");
        BtnUpdateProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateProdukActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUpdateProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        BtnDeleteProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnDeleteProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        BtnDeleteProduk.setText("Delete");
        BtnDeleteProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteProdukActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDeleteProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        BtnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(BtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Produk", "Nama Produk", "Harga Produk", "Tanggal Masuk Produk"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 510, 450));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDeleteProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteProdukActionPerformed
        TxtIDProduk.setEditable(false);
        TxtNamaProduk.setEditable(false);
        TxtHargaProduk.setEditable(false);
        DtcTanggalMasuk.setEnabled(false);

        if (TxtIDProduk.getText().trim().equals("")
                || TxtNamaProduk.getText().trim().equals("")
                || TxtHargaProduk.getText().trim().equals("")
                || DtcTanggalMasuk.getDate() == null) {

            JOptionPane.showMessageDialog(this, "Pilih data dahulu!");
            return;
        } else {
            EntityManagerFactory emf = null;
            EntityManager em = null;

            try {
                emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
                em = emf.createEntityManager();

                String idProduk = TxtIDProduk.getText();

                em.getTransaction().begin();
                Produk k = em.find(Produk.class, idproduk);

                if (k == null) {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                } else {
                    em.remove(k);
                    em.getTransaction().commit();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    showTable();
                    bersih();
                }
            } catch (Exception e) {
                if (em != null && em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
            } finally {
                if (em != null) {
                    em.close();
                }
                if (emf != null) {
                    emf.close();
                }
            }
        }
    }//GEN-LAST:event_BtnDeleteProdukActionPerformed

    private void TxtIDProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDProdukActionPerformed

    private void BtnUpdateProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateProdukActionPerformed
        if (TxtIDProduk.getText().trim().equals("")
                || TxtNamaProduk.getText().trim().equals("")
                || TxtHargaProduk.getText().trim().equals("")
                || DtcTanggalMasuk.getDate() == null) {

            JOptionPane.showMessageDialog(this, "Isi semua data!");
            return;
        }

        try {
            // Ambil input baru
            String idProdukBaru = TxtIDProduk.getText().trim();
            String namaProdukBaru = TxtNamaProduk.getText().trim();
            Date tanggalBaru = DtcTanggalMasuk.getDate();
            int hargaBaru;

            try {
                hargaBaru = Integer.parseInt(TxtHargaProduk.getText().trim());
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Harga harus berupa angka!");
                return;
            }

            em.getTransaction().begin();

            // Cek apakah ID diganti
            if (!idProdukBaru.equals(idproduk)) {
                JOptionPane.showMessageDialog(this, "ID Produk tidak boleh diubah!");
                TxtIDProduk.setText(idproduk);
                em.getTransaction().rollback();
                return;
            }
            // Cari data lama berdasarkan ID lama
            Produk p = em.find(Produk.class, idproduk);

            if (p == null) {
                JOptionPane.showMessageDialog(this, "Produk tidak ditemukan!");
                em.getTransaction().rollback();
                return;
            }

            // Update field
            p.setNamaProduk(namaProdukBaru);
            p.setHargaProduk(hargaBaru);
            p.setTanggalMasukProduk(tanggalBaru);

            // Simpan perubahan
            em.merge(p);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Data produk berhasil diperbarui!");
            showTable();
        } catch (Exception e) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnUpdateProdukActionPerformed

    public void bersih() {
        TxtIDProduk.setText("");
        TxtNamaProduk.setText("");
        TxtHargaProduk.setText("");
        DtcTanggalMasuk.setDate(null);
    }

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        bersih();
    }//GEN-LAST:event_BtnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            return;
        }

        // Ambil data dari tabel
        idproduk = jTable1.getValueAt(row, 0).toString();
        namaproduk = jTable1.getValueAt(row, 1).toString();
        hargaproduk = Integer.parseInt(jTable1.getValueAt(row, 2).toString());

        try {
            tanggalmasukproduk = new SimpleDateFormat("dd-MMM-yyyy")
                    .parse(jTable1.getValueAt(row, 3).toString());
        } catch (Exception e) {
            tanggalmasukproduk = null;
        }

        // Tampilkan ke textfield
        TxtIDProduk.setText(idproduk);
        TxtNamaProduk.setText(namaproduk);
        TxtHargaProduk.setText(String.valueOf(hargaproduk));
        DtcTanggalMasuk.setDate(tanggalmasukproduk);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditDeleteProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnDeleteProduk;
    private javax.swing.JButton BtnUpdateProduk;
    private com.toedter.calendar.JDateChooser DtcTanggalMasuk;
    private javax.swing.JTextField TxtHargaProduk;
    private javax.swing.JTextField TxtIDProduk;
    private javax.swing.JTextField TxtNamaProduk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
