/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Huawei
 */
public class AddNewProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProduct
     */
    public AddNewProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnEditData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtIDProduk = new javax.swing.JTextField();
        TxtNamaProduk = new javax.swing.JTextField();
        TxtHargaProduk = new javax.swing.JTextField();
        DtcTanggalMasuk = new com.toedter.calendar.JDateChooser();
        BtnSave = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEditData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEditData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        BtnEditData.setText("Edit Data");
        BtnEditData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditDataActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEditData, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        jLabel1.setText("New Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 23, 130, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Produk");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 119, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Produk");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 159, 108, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Produk");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 199, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Masuk Produk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 237, -1, -1));

        TxtIDProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDProdukActionPerformed(evt);
            }
        });
        getContentPane().add(TxtIDProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 119, 280, -1));

        TxtNamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaProdukActionPerformed(evt);
            }
        });
        getContentPane().add(TxtNamaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 159, 280, -1));

        TxtHargaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHargaProdukActionPerformed(evt);
            }
        });
        getContentPane().add(TxtHargaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 195, 280, -1));
        getContentPane().add(DtcTanggalMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 235, 283, -1));

        BtnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 275, -1, -1));

        BtnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(BtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 275, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-page-background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaProdukActionPerformed

    private void TxtHargaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHargaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHargaProdukActionPerformed

    public void bersih() {
        TxtIDProduk.setText("");
        TxtNamaProduk.setText("");
        TxtHargaProduk.setText("");
        DtcTanggalMasuk.setDate(null);
    }

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        bersih();
    }//GEN-LAST:event_BtnClearActionPerformed

    private void TxtIDProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDProdukActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        if (TxtIDProduk.getText().equals("")
                | TxtNamaProduk.getText().equals("")
                | TxtHargaProduk.getText().equals("")
                | DtcTanggalMasuk.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Isi Semua Kolom Terlebih Dahulu!");
        } else {
            String ID = TxtIDProduk.getText();
            String nama = TxtNamaProduk.getText();
            int harga = Integer.parseInt(TxtHargaProduk.getText());
            Date tanggal = DtcTanggalMasuk.getDate();

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();

            Produk p = em.find(Produk.class, ID);
            if (p != null) {
                JOptionPane.showMessageDialog(null, "Username sudah ada, gunakan username lain!");
                bersih();
                TxtIDProduk.requestFocus();
                em.getTransaction().rollback();
            } else {
                Produk r = new Produk();
                r.setIdProduk(ID);
                r.setNamaProduk(nama);
                r.setHargaProduk(harga);
                r.setTanggalMasukProduk(tanggal);
                em.persist(r);
                em.getTransaction().commit();

                JOptionPane.showMessageDialog(null, "Produk berhasil disimpan");
                bersih();
            }
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnEditDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditDataActionPerformed
        ViewEditDeleteProduct v = new ViewEditDeleteProduct();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnEditDataActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login z = new login();
        z.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnEditData;
    private javax.swing.JButton BtnSave;
    private com.toedter.calendar.JDateChooser DtcTanggalMasuk;
    private javax.swing.JTextField TxtHargaProduk;
    private javax.swing.JTextField TxtIDProduk;
    private javax.swing.JTextField TxtNamaProduk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
