/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import cafeManagementSystem.PlaceOrder;

/**
 *
 * @author Huawei
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnLogOut = new javax.swing.JButton();
        BtnOrder = new javax.swing.JButton();
        BtnBill = new javax.swing.JButton();
        BtnChangePw = new javax.swing.JButton();
        BtnChangeSecurity = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        BtnNewProduk = new javax.swing.JButton();
        BtnProduk = new javax.swing.JButton();
        BtnUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        BtnLogOut.setText("Logout");
        BtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        BtnOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        BtnOrder.setText("Place Order");
        BtnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrderActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        BtnBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Bills & Order Placed Details.png"))); // NOI18N
        BtnBill.setText("View Bill & Order Placed Detail");
        BtnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBillActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        BtnChangePw.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnChangePw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Password.png"))); // NOI18N
        BtnChangePw.setText("Change Password");
        BtnChangePw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChangePwActionPerformed(evt);
            }
        });
        getContentPane().add(BtnChangePw, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        BtnChangeSecurity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnChangeSecurity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Security Question.png"))); // NOI18N
        BtnChangeSecurity.setText("Change Security Question");
        BtnChangeSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChangeSecurityActionPerformed(evt);
            }
        });
        getContentPane().add(BtnChangeSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        BtnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, -1, -1));

        BtnNewProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnNewProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        BtnNewProduk.setText("New Product");
        BtnNewProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewProdukActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNewProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 700, -1, -1));

        BtnProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        BtnProduk.setText("View, Edit & Delete Product");
        BtnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProdukActionPerformed(evt);
            }
        });
        getContentPane().add(BtnProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 700, -1, -1));

        BtnUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
        BtnUser.setText("Verify Users");
        BtnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUserActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 700, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrderActionPerformed
        PlaceOrder p = new PlaceOrder();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnOrderActionPerformed

    private void BtnChangePwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChangePwActionPerformed
        ChangePassword c = new ChangePassword();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnChangePwActionPerformed

    private void BtnNewProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewProdukActionPerformed
        AddNewProduct a = new AddNewProduct();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnNewProdukActionPerformed

    private void BtnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUserActionPerformed
        VerifyUsers u = new VerifyUsers();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnUserActionPerformed

    private void BtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogOutActionPerformed
        login y = new login();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnLogOutActionPerformed

    private void BtnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBillActionPerformed
        ViewBillOrderPlacedDetails v = new ViewBillOrderPlacedDetails();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBillActionPerformed

    private void BtnChangeSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChangeSecurityActionPerformed
        ChangeSecurityQuestion c = new ChangeSecurityQuestion();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnChangeSecurityActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProdukActionPerformed
        ViewEditDeleteProduct w = new ViewEditDeleteProduct();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnProdukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBill;
    private javax.swing.JButton BtnChangePw;
    private javax.swing.JButton BtnChangeSecurity;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnLogOut;
    private javax.swing.JButton BtnNewProduk;
    private javax.swing.JButton BtnOrder;
    private javax.swing.JButton BtnProduk;
    private javax.swing.JButton BtnUser;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
