package cafe.management.system;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Huawei
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CbSecurity = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtUserLogin = new javax.swing.JTextField();
        txtMobileNumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPasswordLogin = new javax.swing.JPasswordField();
        txtAnswer = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClearSignup = new javax.swing.JButton();
        btnExitSignup = new javax.swing.JButton();
        btnForgotPasswordSignup = new javax.swing.JButton();
        btnLoginSignup = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Signup");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 110, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 225, 113, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 270, 84, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 314, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 358, 84, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 400, 84, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Security Question");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 442, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Answer");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 486, 92, -1));

        CbSecurity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih salah satu", "Arah mana kamu tidur?", "Siapa mantan terindahmu?", "Dimana restoran favoritmu?", "Apa nama hewan peliharaanmu?" }));
        CbSecurity.setToolTipText("");
        CbSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbSecurityActionPerformed(evt);
            }
        });
        getContentPane().add(CbSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 350, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 222, 351, -1));

        txtUserLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 267, 351, -1));

        txtMobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 311, 351, -1));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 355, 351, -1));

        txtPasswordLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtPasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 399, 351, 22));

        txtAnswer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 483, 351, -1));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 523, -1, -1));

        btnClearSignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClearSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClearSignup.setText("Clear");
        btnClearSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnClearSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 523, -1, -1));

        btnExitSignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExitSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        btnExitSignup.setText("Exit");
        btnExitSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnExitSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 523, -1, -1));

        btnForgotPasswordSignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnForgotPasswordSignup.setText("Forgot Password ?");
        btnForgotPasswordSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPasswordSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnForgotPasswordSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 584, -1, -1));

        btnLoginSignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoginSignup.setText("Login");
        btnLoginSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoginSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(866, 584, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cafe Management system.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1370, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordLoginActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtName.getText().equals("")
                | txtUserLogin.getText().equals("")
                | txtMobileNumber.getText().equals("")
                | txtAddress.getText().equals("")
                | txtPasswordLogin.getText().equals("")
                | CbSecurity.getSelectedIndex() == 0
                | txtAnswer.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Semua Kolom Terlebih Dahulu!");
        } else {
            String nama = txtName.getText();
            String user = txtUserLogin.getText();
            String nomor = txtMobileNumber.getText();
            String asddress = txtAddress.getText();
            String pw = txtPasswordLogin.getText();
            String securityQuestion = (String) CbSecurity.getSelectedItem();
            String answer = txtAnswer.getText();

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();

            Akun y = em.find(Akun.class, user);
            if (y != null) {
                JOptionPane.showMessageDialog(null, "Username sudah ada, gunakan username lain!");
                bersih();
                txtUserLogin.requestFocus();
                em.getTransaction().rollback();
            } else {
                Akun x = new Akun();
                x.setName(nama);
                x.setUsername(user);
                x.setMobilePhone(nomor);
                x.setAddress(asddress);
                x.setPassword(pw);
                x.setSecurityQuestion(securityQuestion);
                x.setAnswer(answer);
                em.persist(x);
                em.getTransaction().commit();

                JOptionPane.showMessageDialog(null, "Sukses dibuat!");
                bersih();

                login z = new login();
                z.setVisible(true);
                this.dispose();
            }
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitSignupActionPerformed
        login y = new login();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitSignupActionPerformed

    public void bersih() {
        txtName.setText("");
        txtUserLogin.setText("");
        txtMobileNumber.setText("");
        txtAddress.setText("");
        txtPasswordLogin.setText("");
        CbSecurity.setSelectedIndex(0);
        txtAnswer.setText("");
    }

    private void btnClearSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSignupActionPerformed
        bersih();
    }//GEN-LAST:event_btnClearSignupActionPerformed

    private void CbSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbSecurityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbSecurityActionPerformed

    private void btnForgotPasswordSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPasswordSignupActionPerformed
        forgotpassword y = new forgotpassword();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnForgotPasswordSignupActionPerformed

    private void btnLoginSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSignupActionPerformed
        login y = new login();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbSecurity;
    private javax.swing.JButton btnClearSignup;
    private javax.swing.JButton btnExitSignup;
    private javax.swing.JButton btnForgotPasswordSignup;
    private javax.swing.JButton btnLoginSignup;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPasswordLogin;
    private javax.swing.JTextField txtUserLogin;
    // End of variables declaration//GEN-END:variables
}
