/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Huawei
 */
public class ViewBillOrderPlacedDetails extends javax.swing.JFrame {

    private EntityManagerFactory emf;
    private EntityManager em;

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    private void loadData() {
        try {
            Query q = em.createQuery("SELECT p FROM Penjualan p");
            List<Penjualan> hasil = q.getResultList();
            showTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private String listNamaProduk(Collection<Produk> produkList) {
        if (produkList == null || produkList.isEmpty()) {
            return "-";
        }

        StringBuilder sb = new StringBuilder();
        for (Produk p : produkList) {
            sb.append(p.getNamaProduk()).append(", ");
        }
        sb.setLength(sb.length() - 2);
        return sb.toString();
    }

    public ViewBillOrderPlacedDetails() {
        initComponents();
        connect();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BtnDeleteBill = new javax.swing.JButton();
        BtnUpdateBill = new javax.swing.JButton();
        BtnUploadBill = new javax.swing.JButton();
        BtnDownloadBill = new javax.swing.JButton();
        BtnPrintBill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblData = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Bills & Order Placed Details.png"))); // NOI18N
        jLabel1.setText("View Bill & Order Placed Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 275, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1334, 18, -1, -1));

        BtnDeleteBill.setBackground(new java.awt.Color(204, 0, 0));
        BtnDeleteBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnDeleteBill.setForeground(new java.awt.Color(255, 255, 255));
        BtnDeleteBill.setText("Delete");
        BtnDeleteBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteBillActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDeleteBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, -1, 30));

        BtnUpdateBill.setBackground(new java.awt.Color(255, 255, 51));
        BtnUpdateBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnUpdateBill.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdateBill.setText("Update");
        BtnUpdateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateBillActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUpdateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 670, -1, 30));

        BtnUploadBill.setBackground(new java.awt.Color(51, 255, 0));
        BtnUploadBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnUploadBill.setForeground(new java.awt.Color(255, 255, 255));
        BtnUploadBill.setText("Upload");
        BtnUploadBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUploadBillActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUploadBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 670, -1, 30));

        BtnDownloadBill.setBackground(new java.awt.Color(255, 102, 0));
        BtnDownloadBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnDownloadBill.setForeground(new java.awt.Color(255, 255, 255));
        BtnDownloadBill.setText("Download");
        BtnDownloadBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDownloadBillActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDownloadBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 670, -1, 30));

        BtnPrintBill.setBackground(new java.awt.Color(0, 51, 255));
        BtnPrintBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPrintBill.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrintBill.setText("Print");
        BtnPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintBillActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPrintBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 670, -1, 30));

        TblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill ID", "Nama Kasir", "Nama Waiters", "Nama Customers", "Poin Membership", "Tanggal Transaksi", "Nama Produk", "Total Harga", "Jenis Pembayaran", "Status Pembayaran"
            }
        ));
        TblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 1220, 515));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showTable() {
        try {
            em.clear();

            Query q = em.createQuery(
                    "SELECT DISTINCT p FROM Penjualan p "
                    + "LEFT JOIN FETCH p.idKasir "
                    + "LEFT JOIN FETCH p.idWaiters "
                    + "LEFT JOIN FETCH p.idCustomers "
                    + "LEFT JOIN FETCH p.produkCollection "
                    + "LEFT JOIN FETCH p.pembayaranCollection"
            );

            List<Penjualan> hasil = q.getResultList();

            DefaultTableModel tb = new DefaultTableModel(
                    new String[]{"Bill ID", "Nama Kasir", "Nama Waiters", "Nama Customers",
                        "Poin Membership", "Tanggal Transaksi", "Nama Produk", "Total Harga",
                        "Jenis Pembayaran", "Status Pembayaran"}, 0
            );

            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");

            for (Penjualan p : hasil) {

                String tgl = p.getTanggalPenjualan() != null
                        ? sdf.format(p.getTanggalPenjualan()) : "-";

                String daftarProduk = listNamaProduk(p.getProdukCollection());

                String jenisBayar = "-";
                String statusBayar = "-";
                if (p.getPembayaranCollection() != null && !p.getPembayaranCollection().isEmpty()) {
                    Pembayaran pb = p.getPembayaranCollection().iterator().next();
                    if (pb.getIdJenis() != null) {
                        jenisBayar = pb.getIdJenis().getNamaJenis();
                    }
                    if (pb.getStatusBayar() != null) {
                        statusBayar = pb.getStatusBayar();
                    }
                }

                String namaKasir = p.getIdKasir() != null ? p.getIdKasir().getNamaKasir() : "-";
                String namaWaiters = p.getIdWaiters() != null ? p.getIdWaiters().getNamaWaiters() : "-";
                String namaCust = p.getIdCustomers() != null ? p.getIdCustomers().getNamaCustomers() : "-";

                Integer poinMember = 0;
                if (p.getIdCustomers() != null && p.getIdCustomers().getIdMember() != null) {
                    poinMember = p.getIdCustomers().getIdMember().getPoinMember();
                }

                tb.addRow(new Object[]{
                    p.getIdPenjualan(), namaKasir, namaWaiters, namaCust,
                    poinMember, tgl, daftarProduk, p.getTotalHarga(),
                    jenisBayar, statusBayar
                });
            }

            TblData.setModel(tb);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tampil data: " + e.getMessage());
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDataMouseClicked
        int row = TblData.getSelectedRow();

        if (row != -1) {

            String idBill = TblData.getValueAt(row, 0).toString();
            String namaKasir = TblData.getValueAt(row, 1).toString();
            String namaWaiters = TblData.getValueAt(row, 2).toString();
            String namaCustomers = TblData.getValueAt(row, 3).toString();
            String poinMembership = TblData.getValueAt(row, 4).toString();
            String tanggal = TblData.getValueAt(row, 5).toString();
            String produk = TblData.getValueAt(row, 6).toString();
            String total = TblData.getValueAt(row, 7).toString();
            String jenis = TblData.getValueAt(row, 8).toString();
            String status = TblData.getValueAt(row, 9).toString();
        }
    }//GEN-LAST:event_TblDataMouseClicked

    private void BtnDeleteBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteBillActionPerformed
        int row = TblData.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu dari tabel!");
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH);
        Date tanggal = null;
        try {
            String tanggalStr = TblData.getValueAt(row, 5) != null ? TblData.getValueAt(row, 5).toString() : "";
            if (!tanggalStr.isEmpty()) {
                tanggal = sdf.parse(tanggalStr);
            }
        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid: " + e.getMessage());
            return;
        }

        String idBill = TblData.getValueAt(row, 0).toString();
        String namaKasir = TblData.getValueAt(row, 1).toString();
        String namaWaiters = TblData.getValueAt(row, 2).toString();
        String namaCustomers = TblData.getValueAt(row, 3).toString();
        String produk = TblData.getValueAt(row, 6).toString();
        String jenis = TblData.getValueAt(row, 8).toString();
        String status = TblData.getValueAt(row, 9).toString();

        int poinMembership;
        int total;
        try {
            poinMembership = Integer.parseInt(TblData.getValueAt(row, 4).toString());
            total = Integer.parseInt(TblData.getValueAt(row, 7).toString());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Nilai poin atau total harga tidak valid.");
            return;
        }

        java.awt.Frame parentFrame = null;
        java.awt.Window w = SwingUtilities.getWindowAncestor(this);
        if (w instanceof java.awt.Frame) {
            parentFrame = (java.awt.Frame) w;
        }

        DeleteDialogBill dialog = new DeleteDialogBill(parentFrame != null ? parentFrame : new java.awt.Frame(),
                true, idBill, namaKasir, namaWaiters, namaCustomers, poinMembership, produk, tanggal, total, jenis, status);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        showTable();
    }//GEN-LAST:event_BtnDeleteBillActionPerformed

    private void BtnUpdateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateBillActionPerformed
        int row = TblData.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu dari tabel!");
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH);
        Date tanggal = null;
        try {
            String tanggalStr = TblData.getValueAt(row, 5) != null ? TblData.getValueAt(row, 5).toString() : "";
            if (!tanggalStr.isEmpty()) {
                tanggal = sdf.parse(tanggalStr);
            }
        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid: " + e.getMessage());
            return;
        }

        String idBill = TblData.getValueAt(row, 0).toString();
        String namaKasir = TblData.getValueAt(row, 1).toString();
        String namaWaiters = TblData.getValueAt(row, 2).toString();
        String namaCustomers = TblData.getValueAt(row, 3).toString();
        String produk = TblData.getValueAt(row, 6).toString();
        String jenis = TblData.getValueAt(row, 8).toString();
        String status = TblData.getValueAt(row, 9).toString();

        int poinMembership;
        int total;
        try {
            poinMembership = Integer.parseInt(TblData.getValueAt(row, 4).toString());
            total = Integer.parseInt(TblData.getValueAt(row, 7).toString());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Nilai poin atau total harga tidak valid.");
            return;
        }

        java.awt.Frame parentFrame = null;
        java.awt.Window w = SwingUtilities.getWindowAncestor(this);
        if (w instanceof java.awt.Frame) {
            parentFrame = (java.awt.Frame) w;
        }

        UpdateDialogBill dialog = new UpdateDialogBill(parentFrame != null ? parentFrame : new java.awt.Frame(),
                true, idBill, namaKasir, namaWaiters, namaCustomers, poinMembership, produk, tanggal, total, jenis, status);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        showTable();

    }//GEN-LAST:event_BtnUpdateBillActionPerformed

    private void BtnPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintBillActionPerformed
        Connection conn = null;
        Statement stmt;
        PreparedStatement pstmt = null;

        String driver = "org.postgresql.Driver";
        String koneksi = "jdbc:postgresql://localhost:5432/ManajemenCafe";
        String user = "postgres";
        String password = "1234";

        JasperReport reports;
        String path = ".\\src\\cafe\\management\\system\\BillOrder.jasper";
        try {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
            } catch (SQLException ex) {
                Logger.getLogger(ViewBillOrderPlacedDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                System.getLogger(ViewBillOrderPlacedDetails.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(ViewBillOrderPlacedDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnPrintBillActionPerformed

    private void BtnUploadBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUploadBillActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);

        if (returnValue != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File filePilihan = jfc.getSelectedFile();
        System.out.println("Yang dipilih : " + filePilihan.getAbsolutePath());

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Cafe_Management_SystemPU");
        EntityManager em = emf.createEntityManager();

        try (BufferedReader br = new BufferedReader(new FileReader(filePilihan))) {

            String baris;
            String pemisah = ";";
            boolean isFirstLine = true;

            while ((baris = br.readLine()) != null) {

                if (isFirstLine) {
                    isFirstLine = false;
                    continue;
                }
                if (baris.trim().isEmpty()) {
                    continue;
                }

                String[] data = baris.split(pemisah);

                if (data.length < 10) {
                    System.out.println("Baris tidak lengkap, dilewati: " + baris);
                    continue;
                }

                String idBill = data[0].trim();
                String namaKasir = data[1].trim();
                String namaWaiters = data[2].trim();
                String namaCustomers = data[3].trim();
                int poin = Integer.parseInt(data[4].trim());
                String tanggalStr = data[5].trim();
                String namaProduk = data[6].trim();
                int totalharga = Integer.parseInt(data[7].trim());
                String jenisPembayaran = data[8].trim();
                String statusPembayaran = data[9].trim();

                java.sql.Date tanggal;
                try {
                    SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
                    java.util.Date parsedDate = sdf.parse(tanggalStr);
                    tanggal = new java.sql.Date(parsedDate.getTime());
                } catch (Exception e) {
                    System.out.println("Format tanggal salah: " + baris);
                    continue;
                }

                if (idBill.isEmpty() || namaKasir.isEmpty() || namaWaiters.isEmpty() || namaCustomers.isEmpty()
                        || tanggalStr.isEmpty() || jenisPembayaran.isEmpty() || statusPembayaran.isEmpty()) {
                    System.out.println("Data kosong ditemukan: " + baris);
                    continue;
                }

                em.getTransaction().begin();

                Penjualan existing = em.find(Penjualan.class, idBill);
                if (existing != null) {
                    System.out.println("ID Bill sudah ada, dilewati: " + idBill);
                    em.getTransaction().rollback();
                    continue;
                }

                Penjualan p = new Penjualan();
                p.setIdPenjualan(idBill);

                List<Kasir> kasirList = em.createQuery(
                        "SELECT k FROM Kasir k WHERE LOWER(k.namaKasir) = :nk", Kasir.class)
                        .setParameter("nk", namaKasir.toLowerCase())
                        .getResultList();
                if (kasirList.isEmpty()) {
                    System.out.println("Kasir tidak ditemukan: " + namaKasir);
                    em.getTransaction().rollback();
                    continue;
                }
                p.setIdKasir(kasirList.get(0));

                List<Waiters> waitersList = em.createQuery(
                        "SELECT w FROM Waiters w WHERE LOWER(w.namaWaiters) = :nw", Waiters.class)
                        .setParameter("nw", namaWaiters.toLowerCase())
                        .getResultList();
                if (waitersList.isEmpty()) {
                    System.out.println("Waiters tidak ditemukan: " + namaWaiters);
                    em.getTransaction().rollback();
                    continue;
                }
                p.setIdWaiters(waitersList.get(0));

                List<Customers> customerList = em.createQuery(
                        "SELECT c FROM Customers c WHERE LOWER(c.namaCustomers) = :nc", Customers.class)
                        .setParameter("nc", namaCustomers.toLowerCase())
                        .getResultList();
                if (customerList.isEmpty()) {
                    System.out.println("Customer tidak ditemukan: " + namaCustomers);
                    em.getTransaction().rollback();
                    continue;
                }
                Customers customers = customerList.get(0);
                p.setIdCustomers(customers);

                Membership m = customers.getIdMember();
                if (m != null) {
                    m.setPoinMember(poin);
                    em.merge(m);
                }

                p.setTanggalPenjualan(tanggal);

                List<Produk> produkCollection = new ArrayList<>();
                if (!namaProduk.equalsIgnoreCase("-")) {
                    String[] multipleProduk = namaProduk.split(",");
                    for (String np : multipleProduk) {
                        np = np.trim();
                        List<Produk> found = em.createQuery(
                                "SELECT p FROM Produk p WHERE LOWER(p.namaProduk) = :np", Produk.class)
                                .setParameter("np", np.toLowerCase())
                                .getResultList();
                        if (found.isEmpty()) {
                            System.out.println("Produk tidak ditemukan: " + np);
                            continue;
                        }
                        produkCollection.add(found.get(0));
                    }
                }
                p.setProdukCollection(produkCollection);

                p.setTotalHarga(totalharga);

                Pembayaran pay = new Pembayaran();
                String newPayId = generateIdPembayaran(em);
                pay.setIdPembayaran(newPayId);

                pay.setIdPenjualan(p);
                pay.setTotalBayar(BigInteger.valueOf(totalharga));
                pay.setTanggalBayar(tanggal);
                pay.setStatusBayar(statusPembayaran);

                List<JenisPembayaran> jenisList = em.createQuery(
                        "SELECT j FROM JenisPembayaran j WHERE LOWER(j.namaJenis) = :nj",
                        JenisPembayaran.class)
                        .setParameter("nj", jenisPembayaran.toLowerCase())
                        .getResultList();

                if (!jenisList.isEmpty()) {
                    pay.setIdJenis(jenisList.get(0));
                }

                em.persist(pay);

                List<Pembayaran> pembayaranList = new ArrayList<>();
                pembayaranList.add(pay);
                p.setPembayaranCollection(pembayaranList);

                em.persist(p);
                em.getTransaction().commit();

                System.out.println("BERHASIL INPUT: " + idBill + " - " + namaCustomers);
            }

            JOptionPane.showMessageDialog(null, "Upload CSV selesai! Semua data berhasil diproses.");
            showTable();

        } catch (Exception ex) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_BtnUploadBillActionPerformed

    private String generateIdPembayaran(EntityManager em) {
        try {
            String lastId = em.createQuery(
                    "SELECT p.idPembayaran FROM Pembayaran p ORDER BY p.idPembayaran DESC",
                    String.class
            ).setMaxResults(1).getSingleResult();

            int numeric = Integer.parseInt(lastId.replace("PB", "")) + 1;
            return String.format("PB%03d", numeric);

        } catch (Exception e) {
            return "PB001"; // Jika belum ada data
        }
    }

    public void exportTableToCSV(JTable table, String filename) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan sebagai CSV");
        fileChooser.setSelectedFile(new File(filename));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            if (!fileToSave.getAbsolutePath().toLowerCase().endsWith(".csv")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".csv");
            }

            try (FileWriter writer = new FileWriter(fileToSave)) {
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                int columnCount = model.getColumnCount();

                for (int i = 0; i < columnCount; i++) {
                    writer.write(model.getColumnName(i));
                    if (i < columnCount - 1) {
                        writer.write(";");
                    }
                }
                writer.write("\n");

                for (int i = 0; i < model.getRowCount(); i++) {
                    for (int j = 0; j < columnCount; j++) {
                        Object value = model.getValueAt(i, j);
                        writer.write(value != null ? value.toString() : "");
                        if (j < columnCount - 1) {
                            writer.write(";");
                        }
                    }
                    writer.write("\n");
                }

                JOptionPane.showMessageDialog(this, "Data berhasil diexport ke: " + fileToSave.getAbsolutePath());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error saat mengexport data: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }


    private void BtnDownloadBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDownloadBillActionPerformed
        exportTableToCSV(TblData, "Data Order.csv");
    }//GEN-LAST:event_BtnDownloadBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBillOrderPlacedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBillOrderPlacedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBillOrderPlacedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBillOrderPlacedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBillOrderPlacedDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDeleteBill;
    private javax.swing.JButton BtnDownloadBill;
    private javax.swing.JButton BtnPrintBill;
    private javax.swing.JButton BtnUpdateBill;
    private javax.swing.JButton BtnUploadBill;
    private javax.swing.JTable TblData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
